# 
import requests
import json

# The geographic location of your virtual radar
Latitude = "52.0688114"
Longitude = "19.4709897"

# Range of your virtual radar in kilometers
Radius = "450"

# ADS-B Data URL
URL = "https://public-api.adsbexchange.com/VirtualRadar/AircraftList.json?lat="+Latitude+"&lng="+Longitude+"&fDstU="+Radius

# Unfortunately adsbexchange.com blocks requests generated by urllib so we have to spoof some headers
Headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"}

# Download data from given URL
RawFlightData = requests.get(URL, headers=Headers)

# Parse downloaded JSON
FlightData = json.loads(RawFlightData.content)

